---
- name: Set up Headscale
  become: "{{ headscale_become }}"
  become_user: "{{ headscale_become_user }}"
  block:

    - name: Ensure headscale group exits
      ansible.builtin.group:
        name: headscale
        system: true

    - name: Ensure headscale user exists and has restrictive settings
      ansible.builtin.user:
        name: headscale
        groups: headscale
        password: "*"
        home: /var/lib/headscale
        system: true
        shell: /usr/sbin/nologin

    - name: Ensure that the directory where we deploy headscale exists
      ansible.builtin.file:
        path: "{{ headscale_dir }}"
        state: directory
        owner: headscale
        group: headscale
        mode: "0750"

    - name: Download headscale in {{ headscale_dir }}
      ansible.builtin.get_url:
        url: "{{ headscale_download_url }}"
        dest: "{{ headscale_dir }}"
        checksum: "sha256:{{ headscale_tarball_sha256 }}"
        mode: "0750"
      changed_when: false

    - name: Copy headscale binary to {{ headscale_dir }}/headscale
      ansible.builtin.copy:
        src: "{{ headscale_dir }}/{{ headscale_binary }}"
        dest: /usr/bin/headscale
        remote_src: true
        owner: headscale
        group: headscale
        mode: "0750"

    - name: Remove original downloaded headscale binary
      ansible.builtin.file:
        path: "{{ headscale_dir }}/{{ headscale_binary }}"
        state: absent
      changed_when: false

    - name: Ensure that the directory for headscale configuration exists
      ansible.builtin.file:
        path: /etc/headscale
        state: directory
        owner: headscale
        group: headscale
        mode: "0750"

    - name: Ensure that the headscale SQLite database exists
      ansible.builtin.file:
        path: /var/lib/headscale/db.sqlite
        state: touch
        owner: headscale
        group: headscale
        mode: "0750"
        modification_time: preserve
        access_time: preserve

    - name: Install headscale systemd unit file
      ansible.builtin.template:
        src: etc/systemd/system/headscale.service.j2
        dest: /etc/systemd/system/headscale.service
        mode: "0640"
      notify:
        - systemctl daemon-reload

    - name: Set headscale config file
      ansible.builtin.template:
        src: templates/etc/headscale/config.yaml.j2
        dest: /etc/headscale/config.yaml
        owner: headscale
        group: headscale
        mode: '0640'
      notify: systemctl restart headscale

    - name: Systemctl enable headscale
      ansible.builtin.systemd:
        name: headscale
        enabled: true

    - name: Ensure headscale is running
      ansible.builtin.systemd:
        name: headscale
        state: started

    - name: Wait for headscale to be ready
      ansible.builtin.wait_for:
        host: localhost
        port: 8080
        delay: 5
        timeout: 300
      register: headscale_ready
      until: headscale_ready is succeeded
      retries: 60
