---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role:
          - headscale

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible podman molecule[podman] molecule-plugins[podman]
      - name: Save vault password to file
        run: echo "${{ secrets.ANSIBLE_VAULT }}" > ./.ansible_vault

      - name: Run Molecule tests.
        working-directory: ${{ matrix.role }}
        run: molecule test -s headscale
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
